#!/bin/sh -ex
# Utility functions for use with Travis CI (travis-ci.org).
#
# Copyright (C) 2012 LuaDist.
# Created by David Manura.
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the COPYRIGHT file distributed with LuaDist.
# Please note that the package source code is licensed under its own license.

# recommend TOOL/COMPILER environment variable combinations for standard rules:
#- TOOL=""                     # Use native compiler (GCC usually)
#- COMPILER="clang"            # Use clang
#- TOOL="i686-w64-mingw32"     # 32bit MinGW
#- TOOL="x86_64-w64-mingw32"   # 64bit MinGW
#- TOOL="arm-linux-gnueabihf"  # ARM hard-float (hf), linux
#- TOOL="i586-mingw32msvc"     # old 32bit MinGW

uname -a   # details about system being built on.

[ $TOOL ] && export TOOLFILE="$HOME/$TOOL.cmake"

case "$1" in
  "install")
	sudo dpkg --configure -a
    which cmake || sudo apt-get -qq install cmake
    case "$TOOL|$COMPILER" in
      "i586-mingw32msvc|") which $TOOL-gcc || sudo apt-get -qq install gcc-mingw32 ;;
      "x86_64-w64-mingw32|" | "i686-w64-mingw32|") which $TOOL-gcc || sudo apt-get -qq install gcc-mingw-w64 ;;
      "arm-linux-gnueabihf|") which $TOOL-gcc || sudo apt-get -qq install gcc-arm-linux-gnueabihf ;;
      "|clang") which clang || sudo apt-get -qq install clang ;;
      "|" ) ;;
      * ) echo "ASSERT: $TOOL|$COMPILER"; exit 1 ;;
    esac
    if [ $TOOL ]; then
      echo '' > $TOOLFILE
      echo "set(toolchain $TOOL)" >> $TOOLFILE
      echo "if(toolchain)" >> $TOOLFILE
      echo '  set(toolchain_ ${toolchain}-)' >> $TOOLFILE
      echo "endif()" >> $TOOLFILE
      case "$TOOL" in
        *linux*) echo "set(CMAKE_SYSTEM_NAME Linux)"   >> $TOOLFILE ;;
        *mingw*) echo "set(CMAKE_SYSTEM_NAME Windows)" >> $TOOLFILE ;;
      esac
      echo 'set(CMAKE_C_COMPILER ${toolchain_}gcc)' >> $TOOLFILE
      echo 'set(CMAKE_CXX_COMPILER ${toolchain_}g++)' >> $TOOLFILE
      echo 'set(CMAKE_RC_COMPILER ${toolchain_}windres )' >> $TOOLFILE
      echo 'set(CMAKE_RC_OUTPUT_EXTENSION .obj)' >> $TOOLFILE
      echo 'set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> -O coff <FLAGS> <DEFINES> <SOURCE> <OBJECT>")' >> $TOOLFILE
      echo 'set(CMAKE_FIND_ROOT_PATH /usr/${_toolchain}/ ${CMAKE_INSTALL_PREFIX})' >> $TOOLFILE
      echo 'set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)' >> $TOOLFILE
      echo 'set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)' >> $TOOLFILE
    fi
  ;;
  "bootstrap")
    git clone --recursive git://github.com/LuaDist/bootstrap.git _luadist >/dev/null 2>&1
    (cd _luadist && ./bootstrap >/dev/null 2>&1)
    ln -s "$PWD/_luadist/_install/bin/luadist" ~/luadist
  ;;
  "build")
	[ $COMPILER ] && export CC=$COMPILER
    export MODULE=`basename $PWD`
    ~/luadist _test install $MODULE-scm -verbose -DCMAKE_TOOLCHAIN_FILE=$TOOLFILE
  ;;
  *)
    echo "travis: missing argument $1"
    exit 1
  ;;
esac
